services:
  postgres:
    image: postgres:16.2
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  app:
    build: .
    user: 'root'
    volumes:
      - .:/rails
    # ports:
    #   - 3000:3000
    depends_on:
      - postgres
    environment:
      POSTGRESQL_HOST: postgres
      RAILS_ENV: development
