services:
  postgres:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

  sneakers:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/rake sneakers:run
    volumes:
      - .:/rails
    depends_on:
      - rabbitmq
      - postgres
    environment:
      POSTGRESQL_HOST: postgres
      RABBITMQ_HOST: amqp://guest:guest@rabbitmq:5672

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
    command: /bin/bash -c "bin/setup && bin/rails s -b 0.0.0.0 -p 3030"
    ports:
      - 3030:3030
    depends_on:
      - rabbitmq
      - sneakers
      - postgres
    environment:
      POSTGRESQL_HOST: postgres
      RABBITMQ_HOST: amqp://guest:guest@rabbitmq:5672
    networks:
      default:
        aliases:
          - policyzinha-service

networks:
  default:
    driver: bridge
