services:
  postgres:
    image: postgres:16.2
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  app:
    build: .
    volumes:
      - .:/rails
    command: /bin/bash -c "bin/setup && bin/rails s -b 0.0.0.0"
    # ports:
    #   - 3000:3000
    depends_on:
      - postgres
    environment:
      POSTGRESQL_HOST: postgres
    networks:
      default:
        aliases:
          - policyzinha-service

networks:
  default:
    driver: bridge
