default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRESQL_USER"] || 'postgres' %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] || 'postgres' %>
  host: <%= ENV["POSTGRESQL_HOST"] || 'localhost' %>
  port: <%= ENV["POSTGRESQL_PORT"] || 5432 %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: policyzinha_service_development

test:
  <<: *default
  database: policyzinha_service_test

production:
  <<: *default
  database: policyzinha_service_production
